[config]

[deploy]
exclude = []
target_require_empty = false

[deploy.windows]
target = '~/AppData/Roaming/nushell'

[deploy.linux]
target = '~/.config/nushell'
[dependencies.simple]
local = []
system = []

[pull]
exclude = ['history.txt']
