[config]

[target]
exclude = []
target_require_empty = false

[target.windows]
directory = '~/.config/oh-my-posh/'

[target.linux]
directory = '~/.config/oh-my-posh/'

[dependencies.simple]
local = []
system = []
