[config]

[deploy]
exclude = []
target_require_empty = false

[deploy.windows]
target = '~/.config/oh-my-posh/'

[deploy.linux]
target = '~/.config/oh-my-posh/'
[dependencies.simple]
local = []
system = []
