[deploy]
exclude = []
target_require_empty = false

[deploy.windows]
exclude = []
target = '~/AppData/Local/nvim'

[deploy.linux]
exclude = []
target = '~/.config/nvim'

[pull]
exclude = ['plugin/**']

[pull.windows]
exclude = []

[pull.linux]
exclude = []
[dependencies.simple]
local = []
system = []
